// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication25.Models;

namespace WebApplication25.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210428155842_init001")]
    partial class init001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication25.Models.FilesInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DataVolume")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FilesInfos");
                });

            modelBuilder.Entity("WebApplication25.Models.IPinfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("IPAddress")
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.ToTable("IpInfo");
                });

            modelBuilder.Entity("WebApplication25.Models.MainTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DataVolume")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateTimeLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FilesInfoId")
                        .HasColumnType("bigint");

                    b.Property<int>("RequestResult")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("_IPinfoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FilesInfoId");

                    b.HasIndex("_IPinfoId");

                    b.ToTable("MainTable");
                });

            modelBuilder.Entity("WebApplication25.Models.MainTable", b =>
                {
                    b.HasOne("WebApplication25.Models.FilesInfo", "FilesInfo")
                        .WithMany()
                        .HasForeignKey("FilesInfoId");

                    b.HasOne("WebApplication25.Models.IPinfo", "_IPinfo")
                        .WithMany()
                        .HasForeignKey("_IPinfoId");

                    b.Navigation("_IPinfo");

                    b.Navigation("FilesInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
